name: 'Selects the Xcode toolchain'
description: 'Checks and Attempts to switch to the toolchain defined by the .xcode-version file. Note: It requires xcodes to be installed on the runner.'
inputs:
  xcode_version:
    description: 'The Xcode version to select'
    required: true
    default: '16.4'
runs:
  using: 'composite'
  steps:
    - name: Switch to .xcode-version
      run: xcodes select ${{ inputs.xcode_version }}
      id: version_switch
      shell: /bin/bash -e {0}
    
    - name: Set env var with .xcode-version value
      if: failure()
      run: |
        echo "XCODE_VERSION=$(cat ${{ inputs.xcode_version }})" >> $GITHUB_ENV
      shell: /bin/bash -e {0}
