version: 2
updates:
  - package-ecosystem: swift
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      swift-minor-patch:
        update-types: ["minor", "patch"]
        patterns: ["*"]
    commit-message:
      prefix: "CI (dependabot)"
    labels: ["dependencies", "swiftpm"]
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:15"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      gha-minor-patch:
        update-types: ["minor", "patch"]
        patterns: ["*"]
    commit-message:
      prefix: "CI (dependabot)"
    labels: ["dependencies", "github-actions"]
